algorithm : dreamer-v1
operation :
    save : False
    log_dir : atari-boxing-v4
    device : cuda
environment :
    benchmark : car
    task_name : MultiCarRacing-v1
    seed : 0
    height : 64
    width : 64
    frame_skip : 4
    pixel_norm : True
parameters :
    dreamer :
        train_iterations : 2
        horizon_length : 50
        batch_size : 15
        batch_length : 50
        collect_interval : 10
        num_interaction_episodes : 1
        seed_episodes : 5
        num_evaluate : 3
        
        kl_divergence_scale : 1
        free_nats : 3
        discount : 0.99
        lambda_ : 0.95
        
        use_continue_flag : True
        actor_learning_rate : 0.0001
        critic_learning_rate : 0.0006
        model_learning_rate : 0.0006
        grad_norm_type : 2
        clip_grad : 100
        
        deterministic_size : 512
        stochastic_size : 64
        embedded_state_size : 512
        buffer :
            capacity : 100000
        
        encoder : 
            depth : 32
            stride : 2
            kernel_size : 4
            activation : SiLU

        decoder : 
            depth : 32
            stride : 2
            kernel_size : 5
            activation : SiLU

        rssm :
            recurrent_model : 
                hidden_size : 1024
                activation : SiLU

            transition_model : 
                hidden_size : 1024
                num_layers : 3
                activation : SiLU
                min_std : 0.1

            representation_model:
                hidden_size : 1024
                num_layers : 3
                activation : SiLU
                min_std : 0.1
            
        reward :
            hidden_size : 512
            num_layers : 4
            activation : SiLU

        continue_ :
            hidden_size : 512
            num_layers : 3
            activation : SiLU
        
        agent :
            actor :
                hidden_size : 512
                min_std : 0.1
                activation : SiLU
                num_layers : 5

            critic : 
                hidden_size : 512
                activation : SiLU
                num_layers : 3 
